### ISSUE TITLE
CompEd TODO's

### ISSUE THREAD

**Issue by JForden** [JForden/AutoTA#108]
### Manditory
- [ ] Document existing code
- [ ] Create documentation to help adopters onload TA-Bot to their uni
- [ ] Backend API rewrite(eta?)
- [ ] Account creation, password reset, etc
- [ ] Pylint RC demo file

### Optional

- [ ] Code page rewrite
- [ ] create a branch of Piston that supports multi-file, TA-bot pulls this by default
- [ ] Create analytics page
- [x] Amend file upload to store key details in database(# of TC passed)
- [ ] Rewrite Backend storage of student files
